Update __init__.py
Among other places, celery/app/trace.py:284 and celery/backends/base.py:251 call

store_result(task_id, result, status, request=request)

With the method overwriting here that parameter is missing and an exception is raised:

Traceback (most recent call last):
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/app/trace.py", line 284, in trace_task
    uuid, retval, SUCCESS, traceback=None, request=task_request
  File "/home/deploy/.virtualenvs/aimcandidate/local/lib/python2.7/site-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
TypeError: _store_result() got an unexpected keyword argument 'request'